/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Balances = IDL.Record({
  'icpBalance' : IDL.Nat,
  'ckusdtBalance' : IDL.Nat,
});

export const idlService = IDL.Service({
  'clearLogs' : IDL.Func([], [], []),
  'getActiveOrders' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'getBalances' : IDL.Func([], [Balances], []),
  'getCanisterPrincipal' : IDL.Func([], [IDL.Text], []),
  'getConfig' : IDL.Func(
      [],
      [
        IDL.Record({
          'intervalSeconds' : IDL.Nat,
          'spreadBps' : IDL.Nat,
          'numOrders' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getLogs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getStatus' : IDL.Func(
      [],
      [
        IDL.Record({
          'lastMidPrice' : IDL.Nat,
          'activeOrderCount' : IDL.Nat,
          'isRunning' : IDL.Bool,
        }),
      ],
      ['query'],
    ),
  'initCanisterPrincipal' : IDL.Func([], [], []),
  'setConfig' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
  'startBot' : IDL.Func([], [], []),
  'stopBot' : IDL.Func([], [], []),
  'withdrawCKUSDT' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'withdrawICP' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Balances = IDL.Record({
    'icpBalance' : IDL.Nat,
    'ckusdtBalance' : IDL.Nat,
  });
  
  return IDL.Service({
    'clearLogs' : IDL.Func([], [], []),
    'getActiveOrders' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'getBalances' : IDL.Func([], [Balances], []),
    'getCanisterPrincipal' : IDL.Func([], [IDL.Text], []),
    'getConfig' : IDL.Func(
        [],
        [
          IDL.Record({
            'intervalSeconds' : IDL.Nat,
            'spreadBps' : IDL.Nat,
            'numOrders' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getLogs' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getStatus' : IDL.Func(
        [],
        [
          IDL.Record({
            'lastMidPrice' : IDL.Nat,
            'activeOrderCount' : IDL.Nat,
            'isRunning' : IDL.Bool,
          }),
        ],
        ['query'],
      ),
    'initCanisterPrincipal' : IDL.Func([], [], []),
    'setConfig' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Nat], [], []),
    'startBot' : IDL.Func([], [], []),
    'stopBot' : IDL.Func([], [], []),
    'withdrawCKUSDT' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'withdrawICP' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };